DEBUG:root:
DEBUG:root: "2017-07-28 16:03:20" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-07-28 16:03:49" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-07-28 16:05:10" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-07-28 16:05:12" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-07-28 16:05:13" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-07-28 16:05:29" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-07-28 16:05:38" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-07-28 16:05:41" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-07-28 16:05:41" FALHA - NO RESTORE DO BACKUP

DEBUG:root: "2017-07-28 16:05:41" CLASSE: BancoDados
DEBUG:root: "2017-07-28 16:05:41" CAMINHO DA CLASSE: python.scripts.bancoDados
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-07-28 16:05:57" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-07-28 16:14:29" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-07-28 16:14:32" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-07-28 16:14:35" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-07-28 16:14:52" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:27:17" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:27:18" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:27:33" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:27:36" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:27:37" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:27:52" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:27:57" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:27:59" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:28:00" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:28:15" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:28:15" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:28:18" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:28:18" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:28:34" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:28:34" SUCESSO - FORAM CANCELADAS TODAS CONEXOES COM O BANCO DE DADOS
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:28:40" SUCESSO - NA CRIACAO DO SNAPSHOT
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:28:40" SUCESSO --  REMOVIDO -- DEV_INFG_CELULAQUALIDADE_HOM_SNAPSHOT
DEBUG:root: "2017-08-03 11:28:40" CLASSE: BancoDados
DEBUG:root: "2017-08-03 11:28:40" CAMINHO DA CLASSE: python.scripts.bancoDados
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:28:52" ERRO TRACEBACK (MOST RECENT CALL LAST):
  FILE "PYMSSQL.PYX", LINE 635, IN PYMSSQL.CONNECT (PYMSSQL.C:10734)
  FILE "_MSSQL.PYX", LINE 1902, IN _MSSQL.CONNECT (_MSSQL.C:21821)
  FILE "_MSSQL.PYX", LINE 637, IN _MSSQL.MSSQLCONNECTION.__INIT__ (_MSSQL.C:6581)
  FILE "_MSSQL.PYX", LINE 1630, IN _MSSQL.MAYBE_RAISE_MSSQLDATABASEEXCEPTION (_MSSQL.C:17524)
_MSSQL.MSSQLDATABASEEXCEPTION: (18456, B"LOGIN FAILED FOR USER 'DEV_INFG_JENKINS'.DB-LIB ERROR MESSAGE 20018, SEVERITY 14:\NGENERAL SQL SERVER ERROR: CHECK MESSAGES FROM THE SQL SERVER\NDB-LIB ERROR MESSAGE 20002, SEVERITY 9:\NADAPTIVE SERVER CONNECTION FAILED (INFOSQLDSV:1433)\N")

DURING HANDLING OF THE ABOVE EXCEPTION, ANOTHER EXCEPTION OCCURRED:

TRACEBACK (MOST RECENT CALL LAST):
  FILE "C:\PROJETO\INFOGLOBO\EQUIPEQA\CONTINUOUS_DELIVERY\TRUNK\PYTHON\SCRIPTS\BANCODADOS.PY", LINE 271, IN REMOVER_SNAPSHOT
    DATABASE=NOME_SNAPSHOT)
  FILE "PYMSSQL.PYX", LINE 641, IN PYMSSQL.CONNECT (PYMSSQL.C:10824)
PYMSSQL.OPERATIONALERROR: (18456, B"LOGIN FAILED FOR USER 'DEV_INFG_JENKINS'.DB-LIB ERROR MESSAGE 20018, SEVERITY 14:\NGENERAL SQL SERVER ERROR: CHECK MESSAGES FROM THE SQL SERVER\NDB-LIB ERROR MESSAGE 20002, SEVERITY 9:\NADAPTIVE SERVER CONNECTION FAILED (INFOSQLDSV:1433)\N")

DURING HANDLING OF THE ABOVE EXCEPTION, ANOTHER EXCEPTION OCCURRED:

TRACEBACK (MOST RECENT CALL LAST):
  FILE "C:\PROJETO\INFOGLOBO\EQUIPEQA\CONTINUOUS_DELIVERY\TRUNK\PYTHON\ENVIO_EMAIL\ENVIO_EMAIL.PY", LINE 66, IN ENVIAR_EMAIL
    SERVIDOR.SENDMAIL(SELF.REMETENTE, LISTA_DESTINATARIOS, SELF.MSG.AS_STRING())
  FILE "C:\USERS\RFONSECA\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON35-32\LIB\SMTPLIB.PY", LINE 872, IN SENDMAIL
    RAISE SMTPRECIPIENTSREFUSED(SENDERRS)
SMTPLIB.SMTPRECIPIENTSREFUSED: {' RENATO.FONSECA@INFOGLOBO.COM.BR': (421, B'4.7.0 SMTP4.INFOGLOBO.COM.BR ERROR: TOO MANY ERRORS'), 'RODRIGO.MAIA@INFOGLOBO.COM.BR': (554, B'5.7.1 <RODRIGO.MAIA@INFOGLOBO.COM.BR>: RELAY ACCESS DENIED'), ' GABRIELA.SILVA@INFOGLOBO.COM.BR': (554, B'5.7.1 <GABRIELA.SILVA@INFOGLOBO.COM.BR>: RELAY ACCESS DENIED'), ' VICTOR.FARIAS@INFOGLOBO.COM.BR': (554, B'5.7.1 <VICTOR.FARIAS@INFOGLOBO.COM.BR>: RELAY ACCESS DENIED')}

DEBUG:root: "2017-08-03 11:28:52" CLASSE: Email
DEBUG:root: "2017-08-03 11:28:52" CAMINHO DA CLASSE: python.envio_email.envio_email
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:28:55" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:29:02" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:29:05" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:29:21" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:29:21" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:29:24" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:29:28" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:29:43" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:30:03" TABELA MIGRATE CRIADA COM SUCESSO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:30:05" TABELA BRANCH CRIADA COM SUCESSO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:30:07" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:30:15" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:30:30" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:30:30" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:30:33" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:30:33" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:30:48" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:30:50" TABELA MIGRATE CRIADA COM SUCESSO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:30:52" TABELA BRANCH CRIADA COM SUCESSO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:30:54" COMANDO EXECUATDO FLYWAY..:-USER=DEV_INFG_JENKINS -PASSWORD=95QLYAFTZ2S8 -URL=JDBC:JTDS:SQLSERVER://INFOSQLDSV/DEV_INFG_CELULAQUALIDADE_DSV -LOCATIONS=FILESYSTEM:C:\PROJETO\INFOGLOBO\EQUIPEQA\CONTINUOUS_DELIVERY\TRUNK\TESTES_WINDOWS/SCRIPTS\STG -TABLE=SCHEMA_MIGRATE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:31:01" DEPLOY REALIZADO COM SUCESSO.
VERSAO SVN...: 1.2
VERSAO STG...: 1.2
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:31:03" TABELA MIGRATE CRIADA COM SUCESSO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:31:06" COMANDO EXECUATDO FLYWAY..:-USER=DEV_INFG_JENKINS -PASSWORD=95QLYAFTZ2S8 -URL=JDBC:JTDS:SQLSERVER://INFOSQLDSV/DEV_INFG_CELULAQUALIDADE_HOM -LOCATIONS=FILESYSTEM:C:\PROJETO\INFOGLOBO\EQUIPEQA\CONTINUOUS_DELIVERY\TRUNK\TESTES_WINDOWS/SCRIPTS\STG -TABLE=SCHEMA_MIGRATE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:31:13" DEPLOY REALIZADO COM SUCESSO.
VERSAO STG...: 1.2
VERSAO PRD...: 1.2
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:31:19" ERRO TRACEBACK (MOST RECENT CALL LAST):
  FILE "C:\PROJETO\INFOGLOBO\EQUIPEQA\CONTINUOUS_DELIVERY\TRUNK\PYTHON\ENVIO_EMAIL\ENVIO_EMAIL.PY", LINE 66, IN ENVIAR_EMAIL
    SERVIDOR.SENDMAIL(SELF.REMETENTE, LISTA_DESTINATARIOS, SELF.MSG.AS_STRING())
  FILE "C:\USERS\RFONSECA\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON35-32\LIB\SMTPLIB.PY", LINE 872, IN SENDMAIL
    RAISE SMTPRECIPIENTSREFUSED(SENDERRS)
SMTPLIB.SMTPRECIPIENTSREFUSED: {' RENATO.FONSECA@INFOGLOBO.COM.BR': (421, B'4.7.0 SMTP4.INFOGLOBO.COM.BR ERROR: TOO MANY ERRORS'), 'RODRIGO.MAIA@INFOGLOBO.COM.BR': (554, B'5.7.1 <RODRIGO.MAIA@INFOGLOBO.COM.BR>: RELAY ACCESS DENIED'), ' GABRIELA.SILVA@INFOGLOBO.COM.BR': (554, B'5.7.1 <GABRIELA.SILVA@INFOGLOBO.COM.BR>: RELAY ACCESS DENIED'), ' VICTOR.FARIAS@INFOGLOBO.COM.BR': (554, B'5.7.1 <VICTOR.FARIAS@INFOGLOBO.COM.BR>: RELAY ACCESS DENIED')}

DEBUG:root: "2017-08-03 11:31:19" CLASSE: Email
DEBUG:root: "2017-08-03 11:31:19" CAMINHO DA CLASSE: python.envio_email.envio_email
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:31:21" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:31:24" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:31:39" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:31:42" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:31:47" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:32:02" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:32:04" TABELA MIGRATE CRIADA COM SUCESSO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:32:06" TABELA BRANCH CRIADA COM SUCESSO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:32:07" COMANDO EXECUATDO FLYWAY..:-USER=DEV_INFG_JENKINS -PASSWORD=95QLYAFTZ2S8 -URL=JDBC:JTDS:SQLSERVER://INFOSQLDSV/DEV_INFG_CELULAQUALIDADE_HOM -LOCATIONS=FILESYSTEM:C:\PROJETO\INFOGLOBO\EQUIPEQA\CONTINUOUS_DELIVERY\TRUNK\TESTES_WINDOWS/SCRIPTS\STG -TABLE=SCHEMA_MIGRATE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:32:14" DEPLOY REALIZADO COM SUCESSO.
VERSAO SVN...: 1.2
VERSAO STG...: 1.2
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:32:14" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:32:16" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:32:17" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:32:35" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:32:38" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:32:39" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:32:54" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:32:55" TABELA MIGRATE CRIADA COM SUCESSO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:32:57" TABELA BRANCH CRIADA COM SUCESSO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:32:58" COMANDO EXECUATDO FLYWAY..:-USER=DEV_INFG_JENKINS -PASSWORD=95QLYAFTZ2S8 -URL=JDBC:JTDS:SQLSERVER://INFOSQLDSV/DEV_INFG_CELULAQUALIDADE_HOM -LOCATIONS=FILESYSTEM:C:\PROJETO\INFOGLOBO\EQUIPEQA\CONTINUOUS_DELIVERY\TRUNK\TESTES_WINDOWS/SCRIPTS\STG -TABLE=SCHEMA_MIGRATE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:33:05" DEPLOY REALIZADO COM SUCESSO.
VERSAO SVN...: 1.2
VERSAO STG...: 1.2
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:33:06" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:33:08" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:33:09" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:33:24" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:33:27" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:33:29" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:33:44" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:33:44" SUCESSO - FORAM CANCELADAS TODAS CONEXOES COM O BANCO DE DADOS
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:33:54" SUCESSO - NA CRIACAO DO SNAPSHOT
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:33:54" SUCESSO - FORAM CANCELADAS TODAS CONEXOES COM O BANCO DE DADOS
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:33:59" SUCESSO - AO HABILITAR USUARIO DA APLICACAO COM ACESSO COM O BANCO DE DADOS
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:33:59" FALHA - JA EXISTE UM SNAPSHOT CRIADO PARA ESSE BANCO

DEBUG:root: "2017-08-03 11:33:59" CLASSE: BancoDados
DEBUG:root: "2017-08-03 11:33:59" CAMINHO DA CLASSE: python.scripts.bancoDados
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:34:00" SUCESSO --  REMOVIDO -- DEV_INFG_CELULAQUALIDADE_HOM_SNAPSHOT
DEBUG:root: "2017-08-03 11:34:00" CLASSE: BancoDados
DEBUG:root: "2017-08-03 11:34:00" CAMINHO DA CLASSE: python.scripts.bancoDados
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:34:06" ERRO TRACEBACK (MOST RECENT CALL LAST):
  FILE "PYMSSQL.PYX", LINE 635, IN PYMSSQL.CONNECT (PYMSSQL.C:10734)
  FILE "_MSSQL.PYX", LINE 1902, IN _MSSQL.CONNECT (_MSSQL.C:21821)
  FILE "_MSSQL.PYX", LINE 637, IN _MSSQL.MSSQLCONNECTION.__INIT__ (_MSSQL.C:6581)
  FILE "_MSSQL.PYX", LINE 1630, IN _MSSQL.MAYBE_RAISE_MSSQLDATABASEEXCEPTION (_MSSQL.C:17524)
_MSSQL.MSSQLDATABASEEXCEPTION: (18456, B'DB-LIB ERROR MESSAGE 20018, SEVERITY 11:\NGENERAL SQL SERVER ERROR: CHECK MESSAGES FROM THE SQL SERVER\NDB-LIB ERROR MESSAGE 20018, SEVERITY 14:\NGENERAL SQL SERVER ERROR: CHECK MESSAGES FROM THE SQL SERVER\NDB-LIB ERROR MESSAGE 20002, SEVERITY 9:\NADAPTIVE SERVER CONNECTION FAILED (INFOSQLDSV:1433)\N')

DURING HANDLING OF THE ABOVE EXCEPTION, ANOTHER EXCEPTION OCCURRED:

TRACEBACK (MOST RECENT CALL LAST):
  FILE "C:\PROJETO\INFOGLOBO\EQUIPEQA\CONTINUOUS_DELIVERY\TRUNK\PYTHON\SCRIPTS\BANCODADOS.PY", LINE 271, IN REMOVER_SNAPSHOT
    DATABASE=NOME_SNAPSHOT)
  FILE "PYMSSQL.PYX", LINE 641, IN PYMSSQL.CONNECT (PYMSSQL.C:10824)
PYMSSQL.OPERATIONALERROR: (18456, B'DB-LIB ERROR MESSAGE 20018, SEVERITY 11:\NGENERAL SQL SERVER ERROR: CHECK MESSAGES FROM THE SQL SERVER\NDB-LIB ERROR MESSAGE 20018, SEVERITY 14:\NGENERAL SQL SERVER ERROR: CHECK MESSAGES FROM THE SQL SERVER\NDB-LIB ERROR MESSAGE 20002, SEVERITY 9:\NADAPTIVE SERVER CONNECTION FAILED (INFOSQLDSV:1433)\N')

DURING HANDLING OF THE ABOVE EXCEPTION, ANOTHER EXCEPTION OCCURRED:

TRACEBACK (MOST RECENT CALL LAST):
  FILE "C:\PROJETO\INFOGLOBO\EQUIPEQA\CONTINUOUS_DELIVERY\TRUNK\PYTHON\ENVIO_EMAIL\ENVIO_EMAIL.PY", LINE 66, IN ENVIAR_EMAIL
    SERVIDOR.SENDMAIL(SELF.REMETENTE, LISTA_DESTINATARIOS, SELF.MSG.AS_STRING())
  FILE "C:\USERS\RFONSECA\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON35-32\LIB\SMTPLIB.PY", LINE 872, IN SENDMAIL
    RAISE SMTPRECIPIENTSREFUSED(SENDERRS)
SMTPLIB.SMTPRECIPIENTSREFUSED: {' RENATO.FONSECA@INFOGLOBO.COM.BR': (421, B'4.7.0 SMTP4.INFOGLOBO.COM.BR ERROR: TOO MANY ERRORS'), 'RODRIGO.MAIA@INFOGLOBO.COM.BR': (554, B'5.7.1 <RODRIGO.MAIA@INFOGLOBO.COM.BR>: RELAY ACCESS DENIED'), ' GABRIELA.SILVA@INFOGLOBO.COM.BR': (554, B'5.7.1 <GABRIELA.SILVA@INFOGLOBO.COM.BR>: RELAY ACCESS DENIED'), ' VICTOR.FARIAS@INFOGLOBO.COM.BR': (554, B'5.7.1 <VICTOR.FARIAS@INFOGLOBO.COM.BR>: RELAY ACCESS DENIED')}

DEBUG:root: "2017-08-03 11:34:06" CLASSE: Email
DEBUG:root: "2017-08-03 11:34:06" CAMINHO DA CLASSE: python.envio_email.envio_email
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:34:06" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:34:09" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:34:10" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:34:25" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:34:25" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:34:28" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:34:29" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:34:44" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:34:44" FALHA - CRIACAO DO BACKUP.

DEBUG:root: "2017-08-03 11:34:44" CLASSE: BancoDados
DEBUG:root: "2017-08-03 11:34:44" CAMINHO DA CLASSE: python.scripts.bancoDados
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:34:45" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:34:47" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:34:47" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:35:03" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:35:03" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:35:05" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:35:06" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:35:21" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:35:23" TABELA MIGRATE CRIADA COM SUCESSO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:35:24" TABELA BRANCH CRIADA COM SUCESSO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:35:24" NAO FOI ENCONTRADO NENHUM SCRIPT SQL PARA SER EXECUTADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:35:25" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:35:28" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:35:28" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:35:44" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:35:46" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:35:47" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:36:03" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:36:06" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:36:09" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:36:09" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:36:24" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:36:25" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:36:27" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:36:28" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:36:43" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:36:44" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:36:47" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:36:47" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:37:03" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:37:03" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:37:05" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:37:07" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:37:22" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:37:22" SUCESSO - FORAM CANCELADAS TODAS CONEXOES COM O BANCO DE DADOS
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:37:28" SUCESSO - NA CRIACAO DO SNAPSHOT
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:37:29" TABELA MIGRATE CRIADA COM SUCESSO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:37:30" TABELA BRANCH CRIADA COM SUCESSO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:37:32" COMANDO EXECUATDO FLYWAY..:-USER=DEV_INFG_JENKINS -PASSWORD=95QLYAFTZ2S8 -URL=JDBC:JTDS:SQLSERVER://INFOSQLDSV/DEV_INFG_CELULAQUALIDADE_HOM -LOCATIONS=FILESYSTEM:C:\PROJETO\INFOGLOBO\EQUIPEQA\CONTINUOUS_DELIVERY\TRUNK\TESTES_WINDOWS/SCRIPTS\STG -TABLE=SCHEMA_MIGRATE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:37:38" DEPLOY REALIZADO COM SUCESSO.
VERSAO SVN...: 1.2
VERSAO STG...: 1.2
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:37:38" SUCESSO - FORAM CANCELADAS TODAS CONEXOES COM O BANCO DE DADOS
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:37:39" REALIZANDO O FAILBACK

DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:37:39" SUCESSO - AO HABILITAR USUARIO DA APLICACAO COM ACESSO COM O BANCO DE DADOS
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:37:40" SUCESSO --  REMOVIDO -- DEV_INFG_CELULAQUALIDADE_HOM_SNAPSHOT
DEBUG:root: "2017-08-03 11:37:40" CLASSE: BancoDados
DEBUG:root: "2017-08-03 11:37:40" CAMINHO DA CLASSE: python.scripts.bancoDados
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:37:46" ERRO TRACEBACK (MOST RECENT CALL LAST):
  FILE "PYMSSQL.PYX", LINE 635, IN PYMSSQL.CONNECT (PYMSSQL.C:10734)
  FILE "_MSSQL.PYX", LINE 1902, IN _MSSQL.CONNECT (_MSSQL.C:21821)
  FILE "_MSSQL.PYX", LINE 637, IN _MSSQL.MSSQLCONNECTION.__INIT__ (_MSSQL.C:6581)
  FILE "_MSSQL.PYX", LINE 1630, IN _MSSQL.MAYBE_RAISE_MSSQLDATABASEEXCEPTION (_MSSQL.C:17524)
_MSSQL.MSSQLDATABASEEXCEPTION: (18456, B'DB-LIB ERROR MESSAGE 20018, SEVERITY 11:\NGENERAL SQL SERVER ERROR: CHECK MESSAGES FROM THE SQL SERVER\NDB-LIB ERROR MESSAGE 20018, SEVERITY 14:\NGENERAL SQL SERVER ERROR: CHECK MESSAGES FROM THE SQL SERVER\NDB-LIB ERROR MESSAGE 20002, SEVERITY 9:\NADAPTIVE SERVER CONNECTION FAILED (INFOSQLDSV:1433)\N')

DURING HANDLING OF THE ABOVE EXCEPTION, ANOTHER EXCEPTION OCCURRED:

TRACEBACK (MOST RECENT CALL LAST):
  FILE "C:\PROJETO\INFOGLOBO\EQUIPEQA\CONTINUOUS_DELIVERY\TRUNK\PYTHON\SCRIPTS\BANCODADOS.PY", LINE 271, IN REMOVER_SNAPSHOT
    DATABASE=NOME_SNAPSHOT)
  FILE "PYMSSQL.PYX", LINE 641, IN PYMSSQL.CONNECT (PYMSSQL.C:10824)
PYMSSQL.OPERATIONALERROR: (18456, B'DB-LIB ERROR MESSAGE 20018, SEVERITY 11:\NGENERAL SQL SERVER ERROR: CHECK MESSAGES FROM THE SQL SERVER\NDB-LIB ERROR MESSAGE 20018, SEVERITY 14:\NGENERAL SQL SERVER ERROR: CHECK MESSAGES FROM THE SQL SERVER\NDB-LIB ERROR MESSAGE 20002, SEVERITY 9:\NADAPTIVE SERVER CONNECTION FAILED (INFOSQLDSV:1433)\N')

DURING HANDLING OF THE ABOVE EXCEPTION, ANOTHER EXCEPTION OCCURRED:

TRACEBACK (MOST RECENT CALL LAST):
  FILE "C:\PROJETO\INFOGLOBO\EQUIPEQA\CONTINUOUS_DELIVERY\TRUNK\PYTHON\ENVIO_EMAIL\ENVIO_EMAIL.PY", LINE 66, IN ENVIAR_EMAIL
    SERVIDOR.SENDMAIL(SELF.REMETENTE, LISTA_DESTINATARIOS, SELF.MSG.AS_STRING())
  FILE "C:\USERS\RFONSECA\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON35-32\LIB\SMTPLIB.PY", LINE 872, IN SENDMAIL
    RAISE SMTPRECIPIENTSREFUSED(SENDERRS)
SMTPLIB.SMTPRECIPIENTSREFUSED: {' RENATO.FONSECA@INFOGLOBO.COM.BR': (421, B'4.7.0 SMTP4.INFOGLOBO.COM.BR ERROR: TOO MANY ERRORS'), 'RODRIGO.MAIA@INFOGLOBO.COM.BR': (554, B'5.7.1 <RODRIGO.MAIA@INFOGLOBO.COM.BR>: RELAY ACCESS DENIED'), ' GABRIELA.SILVA@INFOGLOBO.COM.BR': (554, B'5.7.1 <GABRIELA.SILVA@INFOGLOBO.COM.BR>: RELAY ACCESS DENIED'), ' VICTOR.FARIAS@INFOGLOBO.COM.BR': (554, B'5.7.1 <VICTOR.FARIAS@INFOGLOBO.COM.BR>: RELAY ACCESS DENIED')}

DEBUG:root: "2017-08-03 11:37:46" CLASSE: Email
DEBUG:root: "2017-08-03 11:37:46" CAMINHO DA CLASSE: python.envio_email.envio_email
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:37:47" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:37:49" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:37:50" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:38:05" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:38:06" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:38:08" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:38:09" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:38:24" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:38:24" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:38:25" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:38:27" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:38:29" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:38:44" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:58:19" TABELA MIGRATE CRIADA COM SUCESSO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:58:21" TABELA BRANCH CRIADA COM SUCESSO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 11:59:00" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:03:41" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:03:44" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:03:45" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:04:00" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:04:05" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:04:06" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:04:21" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:04:21" SUCESSO - FORAM CANCELADAS TODAS CONEXOES COM O BANCO DE DADOS
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:04:26" SUCESSO - NA CRIACAO DO SNAPSHOT
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:04:28" COMANDO EXECUATDO FLYWAY..:-USER=DEV_INFG_JENKINS -PASSWORD=95QLYAFTZ2S8 -URL=JDBC:JTDS:SQLSERVER://INFOSQLDSV/DEV_INFG_CELULAQUALIDADE_HOM -LOCATIONS=FILESYSTEM:C:\PROJETO\INFOGLOBO\EQUIPEQA\CONTINUOUS_DELIVERY\TRUNK\TESTES_WINDOWS/SCRIPTS\STG -TABLE=SCHEMA_MIGRATE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:04:35" DEPLOY REALIZADO COM SUCESSO.
VERSAO SVN...: 1.2
VERSAO STG...: 1.2
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:04:35" SUCESSO - FORAM CANCELADAS TODAS CONEXOES COM O BANCO DE DADOS
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:04:35" REALIZANDO O FAILBACK

DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:04:35" SUCESSO - AO HABILITAR USUARIO DA APLICACAO COM ACESSO COM O BANCO DE DADOS
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:04:36" SUCESSO --  REMOVIDO -- DEV_INFG_CELULAQUALIDADE_HOM_SNAPSHOT
DEBUG:root: "2017-08-03 12:04:36" CLASSE: BancoDados
DEBUG:root: "2017-08-03 12:04:36" CAMINHO DA CLASSE: python.scripts.bancoDados
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:04:42" ERRO TRACEBACK (MOST RECENT CALL LAST):
  FILE "PYMSSQL.PYX", LINE 635, IN PYMSSQL.CONNECT (PYMSSQL.C:10734)
  FILE "_MSSQL.PYX", LINE 1902, IN _MSSQL.CONNECT (_MSSQL.C:21821)
  FILE "_MSSQL.PYX", LINE 637, IN _MSSQL.MSSQLCONNECTION.__INIT__ (_MSSQL.C:6581)
  FILE "_MSSQL.PYX", LINE 1630, IN _MSSQL.MAYBE_RAISE_MSSQLDATABASEEXCEPTION (_MSSQL.C:17524)
_MSSQL.MSSQLDATABASEEXCEPTION: (18456, B"LOGIN FAILED FOR USER 'DEV_INFG_JENKINS'.DB-LIB ERROR MESSAGE 20018, SEVERITY 14:\NGENERAL SQL SERVER ERROR: CHECK MESSAGES FROM THE SQL SERVER\NDB-LIB ERROR MESSAGE 20002, SEVERITY 9:\NADAPTIVE SERVER CONNECTION FAILED (INFOSQLDSV:1433)\N")

DURING HANDLING OF THE ABOVE EXCEPTION, ANOTHER EXCEPTION OCCURRED:

TRACEBACK (MOST RECENT CALL LAST):
  FILE "C:\PROJETO\INFOGLOBO\EQUIPEQA\CONTINUOUS_DELIVERY\TRUNK\PYTHON\SCRIPTS\BANCODADOS.PY", LINE 271, IN REMOVER_SNAPSHOT
    DATABASE=NOME_SNAPSHOT)
  FILE "PYMSSQL.PYX", LINE 641, IN PYMSSQL.CONNECT (PYMSSQL.C:10824)
PYMSSQL.OPERATIONALERROR: (18456, B"LOGIN FAILED FOR USER 'DEV_INFG_JENKINS'.DB-LIB ERROR MESSAGE 20018, SEVERITY 14:\NGENERAL SQL SERVER ERROR: CHECK MESSAGES FROM THE SQL SERVER\NDB-LIB ERROR MESSAGE 20002, SEVERITY 9:\NADAPTIVE SERVER CONNECTION FAILED (INFOSQLDSV:1433)\N")

DURING HANDLING OF THE ABOVE EXCEPTION, ANOTHER EXCEPTION OCCURRED:

TRACEBACK (MOST RECENT CALL LAST):
  FILE "C:\PROJETO\INFOGLOBO\EQUIPEQA\CONTINUOUS_DELIVERY\TRUNK\PYTHON\ENVIO_EMAIL\ENVIO_EMAIL.PY", LINE 66, IN ENVIAR_EMAIL
    SERVIDOR.SENDMAIL(SELF.REMETENTE, LISTA_DESTINATARIOS, SELF.MSG.AS_STRING())
  FILE "C:\USERS\RFONSECA\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON35-32\LIB\SMTPLIB.PY", LINE 872, IN SENDMAIL
    RAISE SMTPRECIPIENTSREFUSED(SENDERRS)
SMTPLIB.SMTPRECIPIENTSREFUSED: {' VICTOR.FARIAS@INFOGLOBO.COM.BR': (554, B'5.7.1 <VICTOR.FARIAS@INFOGLOBO.COM.BR>: RELAY ACCESS DENIED'), ' RENATO.FONSECA@INFOGLOBO.COM.BR': (421, B'4.7.0 SMTP4.INFOGLOBO.COM.BR ERROR: TOO MANY ERRORS'), 'RODRIGO.MAIA@INFOGLOBO.COM.BR': (554, B'5.7.1 <RODRIGO.MAIA@INFOGLOBO.COM.BR>: RELAY ACCESS DENIED'), ' GABRIELA.SILVA@INFOGLOBO.COM.BR': (554, B'5.7.1 <GABRIELA.SILVA@INFOGLOBO.COM.BR>: RELAY ACCESS DENIED')}

DEBUG:root: "2017-08-03 12:04:42" CLASSE: Email
DEBUG:root: "2017-08-03 12:04:42" CAMINHO DA CLASSE: python.envio_email.envio_email
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:05:49" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:05:51" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:05:52" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:06:07" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:06:10" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:06:17" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:06:32" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:06:32" SUCESSO - FORAM CANCELADAS TODAS CONEXOES COM O BANCO DE DADOS
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:06:42" SUCESSO - NA CRIACAO DO SNAPSHOT
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:06:42" SUCESSO --  REMOVIDO -- DEV_INFG_CELULAQUALIDADE_HOM_SNAPSHOT
DEBUG:root: "2017-08-03 12:06:42" CLASSE: BancoDados
DEBUG:root: "2017-08-03 12:06:42" CAMINHO DA CLASSE: python.scripts.bancoDados
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:06:48" ERRO TRACEBACK (MOST RECENT CALL LAST):
  FILE "PYMSSQL.PYX", LINE 635, IN PYMSSQL.CONNECT (PYMSSQL.C:10734)
  FILE "_MSSQL.PYX", LINE 1902, IN _MSSQL.CONNECT (_MSSQL.C:21821)
  FILE "_MSSQL.PYX", LINE 637, IN _MSSQL.MSSQLCONNECTION.__INIT__ (_MSSQL.C:6581)
  FILE "_MSSQL.PYX", LINE 1630, IN _MSSQL.MAYBE_RAISE_MSSQLDATABASEEXCEPTION (_MSSQL.C:17524)
_MSSQL.MSSQLDATABASEEXCEPTION: (18456, B"LOGIN FAILED FOR USER 'DEV_INFG_JENKINS'.DB-LIB ERROR MESSAGE 20018, SEVERITY 14:\NGENERAL SQL SERVER ERROR: CHECK MESSAGES FROM THE SQL SERVER\NDB-LIB ERROR MESSAGE 20002, SEVERITY 9:\NADAPTIVE SERVER CONNECTION FAILED (INFOSQLDSV:1433)\N")

DURING HANDLING OF THE ABOVE EXCEPTION, ANOTHER EXCEPTION OCCURRED:

TRACEBACK (MOST RECENT CALL LAST):
  FILE "C:\PROJETO\INFOGLOBO\EQUIPEQA\CONTINUOUS_DELIVERY\TRUNK\PYTHON\SCRIPTS\BANCODADOS.PY", LINE 271, IN REMOVER_SNAPSHOT
    DATABASE=NOME_SNAPSHOT)
  FILE "PYMSSQL.PYX", LINE 641, IN PYMSSQL.CONNECT (PYMSSQL.C:10824)
PYMSSQL.OPERATIONALERROR: (18456, B"LOGIN FAILED FOR USER 'DEV_INFG_JENKINS'.DB-LIB ERROR MESSAGE 20018, SEVERITY 14:\NGENERAL SQL SERVER ERROR: CHECK MESSAGES FROM THE SQL SERVER\NDB-LIB ERROR MESSAGE 20002, SEVERITY 9:\NADAPTIVE SERVER CONNECTION FAILED (INFOSQLDSV:1433)\N")

DURING HANDLING OF THE ABOVE EXCEPTION, ANOTHER EXCEPTION OCCURRED:

TRACEBACK (MOST RECENT CALL LAST):
  FILE "C:\PROJETO\INFOGLOBO\EQUIPEQA\CONTINUOUS_DELIVERY\TRUNK\PYTHON\ENVIO_EMAIL\ENVIO_EMAIL.PY", LINE 66, IN ENVIAR_EMAIL
    SERVIDOR.SENDMAIL(SELF.REMETENTE, LISTA_DESTINATARIOS, SELF.MSG.AS_STRING())
  FILE "C:\USERS\RFONSECA\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON35-32\LIB\SMTPLIB.PY", LINE 872, IN SENDMAIL
    RAISE SMTPRECIPIENTSREFUSED(SENDERRS)
SMTPLIB.SMTPRECIPIENTSREFUSED: {' RENATO.FONSECA@INFOGLOBO.COM.BR': (421, B'4.7.0 SMTP4.INFOGLOBO.COM.BR ERROR: TOO MANY ERRORS'), ' VICTOR.FARIAS@INFOGLOBO.COM.BR': (554, B'5.7.1 <VICTOR.FARIAS@INFOGLOBO.COM.BR>: RELAY ACCESS DENIED'), ' GABRIELA.SILVA@INFOGLOBO.COM.BR': (554, B'5.7.1 <GABRIELA.SILVA@INFOGLOBO.COM.BR>: RELAY ACCESS DENIED'), 'RODRIGO.MAIA@INFOGLOBO.COM.BR': (554, B'5.7.1 <RODRIGO.MAIA@INFOGLOBO.COM.BR>: RELAY ACCESS DENIED')}

DEBUG:root: "2017-08-03 12:06:48" CLASSE: Email
DEBUG:root: "2017-08-03 12:06:48" CAMINHO DA CLASSE: python.envio_email.envio_email
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:06:49" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:06:51" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:06:52" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:07:07" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:07:09" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:07:10" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:07:25" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:07:27" TABELA MIGRATE CRIADA COM SUCESSO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:07:28" TABELA BRANCH CRIADA COM SUCESSO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:07:30" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:07:31" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:07:46" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:07:48" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:07:49" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:08:05" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:08:06" TABELA MIGRATE CRIADA COM SUCESSO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:08:07" TABELA BRANCH CRIADA COM SUCESSO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:08:09" COMANDO EXECUATDO FLYWAY..:-USER=DEV_INFG_JENKINS -PASSWORD=95QLYAFTZ2S8 -URL=JDBC:JTDS:SQLSERVER://INFOSQLDSV/DEV_INFG_CELULAQUALIDADE_DSV -LOCATIONS=FILESYSTEM:C:\PROJETO\INFOGLOBO\EQUIPEQA\CONTINUOUS_DELIVERY\TRUNK\TESTES_WINDOWS/SCRIPTS\STG -TABLE=SCHEMA_MIGRATE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:08:15" DEPLOY REALIZADO COM SUCESSO.
VERSAO SVN...: 1.2
VERSAO STG...: 1.2
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:08:17" COMANDO EXECUATDO FLYWAY..:-USER=DEV_INFG_JENKINS -PASSWORD=95QLYAFTZ2S8 -URL=JDBC:JTDS:SQLSERVER://INFOSQLDSV/DEV_INFG_CELULAQUALIDADE_HOM -LOCATIONS=FILESYSTEM:C:\PROJETO\INFOGLOBO\EQUIPEQA\CONTINUOUS_DELIVERY\TRUNK\TESTES_WINDOWS/SCRIPTS\STG -TABLE=SCHEMA_MIGRATE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:08:23" DEPLOY REALIZADO COM SUCESSO.
VERSAO STG...: 1.2
VERSAO PRD...: 1.2
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:08:29" ERRO TRACEBACK (MOST RECENT CALL LAST):
  FILE "C:\PROJETO\INFOGLOBO\EQUIPEQA\CONTINUOUS_DELIVERY\TRUNK\PYTHON\ENVIO_EMAIL\ENVIO_EMAIL.PY", LINE 66, IN ENVIAR_EMAIL
    SERVIDOR.SENDMAIL(SELF.REMETENTE, LISTA_DESTINATARIOS, SELF.MSG.AS_STRING())
  FILE "C:\USERS\RFONSECA\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON35-32\LIB\SMTPLIB.PY", LINE 872, IN SENDMAIL
    RAISE SMTPRECIPIENTSREFUSED(SENDERRS)
SMTPLIB.SMTPRECIPIENTSREFUSED: {' RENATO.FONSECA@INFOGLOBO.COM.BR': (421, B'4.7.0 SMTP4.INFOGLOBO.COM.BR ERROR: TOO MANY ERRORS'), ' VICTOR.FARIAS@INFOGLOBO.COM.BR': (554, B'5.7.1 <VICTOR.FARIAS@INFOGLOBO.COM.BR>: RELAY ACCESS DENIED'), ' GABRIELA.SILVA@INFOGLOBO.COM.BR': (554, B'5.7.1 <GABRIELA.SILVA@INFOGLOBO.COM.BR>: RELAY ACCESS DENIED'), 'RODRIGO.MAIA@INFOGLOBO.COM.BR': (554, B'5.7.1 <RODRIGO.MAIA@INFOGLOBO.COM.BR>: RELAY ACCESS DENIED')}

DEBUG:root: "2017-08-03 12:08:29" CLASSE: Email
DEBUG:root: "2017-08-03 12:08:29" CAMINHO DA CLASSE: python.envio_email.envio_email
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:08:33" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:08:36" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:08:51" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:08:54" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:08:55" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:09:10" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:09:12" COMANDO EXECUATDO FLYWAY..:-USER=DEV_INFG_JENKINS -PASSWORD=95QLYAFTZ2S8 -URL=JDBC:JTDS:SQLSERVER://INFOSQLDSV/DEV_INFG_CELULAQUALIDADE_HOM -LOCATIONS=FILESYSTEM:C:\PROJETO\INFOGLOBO\EQUIPEQA\CONTINUOUS_DELIVERY\TRUNK\TESTES_WINDOWS/SCRIPTS\STG -TABLE=SCHEMA_MIGRATE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:09:18" DEPLOY REALIZADO COM SUCESSO.
VERSAO SVN...: 1.2
VERSAO STG...: 1.2
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:09:19" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:09:21" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:09:22" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:09:38" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:09:40" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:09:41" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:09:58" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:10:02" COMANDO EXECUATDO FLYWAY..:-USER=DEV_INFG_JENKINS -PASSWORD=95QLYAFTZ2S8 -URL=JDBC:JTDS:SQLSERVER://INFOSQLDSV/DEV_INFG_CELULAQUALIDADE_HOM -LOCATIONS=FILESYSTEM:C:\PROJETO\INFOGLOBO\EQUIPEQA\CONTINUOUS_DELIVERY\TRUNK\TESTES_WINDOWS/SCRIPTS\STG -TABLE=SCHEMA_MIGRATE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:10:09" DEPLOY REALIZADO COM SUCESSO.
VERSAO SVN...: 1.2
VERSAO STG...: 1.2
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:10:09" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:10:12" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:10:13" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:10:28" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:10:30" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:10:31" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:10:46" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:10:47" SUCESSO - FORAM CANCELADAS TODAS CONEXOES COM O BANCO DE DADOS
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:10:52" SUCESSO - NA CRIACAO DO SNAPSHOT
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:10:52" SUCESSO - FORAM CANCELADAS TODAS CONEXOES COM O BANCO DE DADOS
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:10:58" SUCESSO - AO HABILITAR USUARIO DA APLICACAO COM ACESSO COM O BANCO DE DADOS
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:10:58" FALHA - JA EXISTE UM SNAPSHOT CRIADO PARA ESSE BANCO

DEBUG:root: "2017-08-03 12:10:58" CLASSE: BancoDados
DEBUG:root: "2017-08-03 12:10:58" CAMINHO DA CLASSE: python.scripts.bancoDados
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:10:58" SUCESSO --  REMOVIDO -- DEV_INFG_CELULAQUALIDADE_HOM_SNAPSHOT
DEBUG:root: "2017-08-03 12:10:58" CLASSE: BancoDados
DEBUG:root: "2017-08-03 12:10:58" CAMINHO DA CLASSE: python.scripts.bancoDados
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:11:04" ERRO TRACEBACK (MOST RECENT CALL LAST):
  FILE "PYMSSQL.PYX", LINE 635, IN PYMSSQL.CONNECT (PYMSSQL.C:10734)
  FILE "_MSSQL.PYX", LINE 1902, IN _MSSQL.CONNECT (_MSSQL.C:21821)
  FILE "_MSSQL.PYX", LINE 637, IN _MSSQL.MSSQLCONNECTION.__INIT__ (_MSSQL.C:6581)
  FILE "_MSSQL.PYX", LINE 1630, IN _MSSQL.MAYBE_RAISE_MSSQLDATABASEEXCEPTION (_MSSQL.C:17524)
_MSSQL.MSSQLDATABASEEXCEPTION: (18456, B'DB-LIB ERROR MESSAGE 20018, SEVERITY 11:\NGENERAL SQL SERVER ERROR: CHECK MESSAGES FROM THE SQL SERVER\NDB-LIB ERROR MESSAGE 20018, SEVERITY 14:\NGENERAL SQL SERVER ERROR: CHECK MESSAGES FROM THE SQL SERVER\NDB-LIB ERROR MESSAGE 20002, SEVERITY 9:\NADAPTIVE SERVER CONNECTION FAILED (INFOSQLDSV:1433)\N')

DURING HANDLING OF THE ABOVE EXCEPTION, ANOTHER EXCEPTION OCCURRED:

TRACEBACK (MOST RECENT CALL LAST):
  FILE "C:\PROJETO\INFOGLOBO\EQUIPEQA\CONTINUOUS_DELIVERY\TRUNK\PYTHON\SCRIPTS\BANCODADOS.PY", LINE 271, IN REMOVER_SNAPSHOT
    DATABASE=NOME_SNAPSHOT)
  FILE "PYMSSQL.PYX", LINE 641, IN PYMSSQL.CONNECT (PYMSSQL.C:10824)
PYMSSQL.OPERATIONALERROR: (18456, B'DB-LIB ERROR MESSAGE 20018, SEVERITY 11:\NGENERAL SQL SERVER ERROR: CHECK MESSAGES FROM THE SQL SERVER\NDB-LIB ERROR MESSAGE 20018, SEVERITY 14:\NGENERAL SQL SERVER ERROR: CHECK MESSAGES FROM THE SQL SERVER\NDB-LIB ERROR MESSAGE 20002, SEVERITY 9:\NADAPTIVE SERVER CONNECTION FAILED (INFOSQLDSV:1433)\N')

DURING HANDLING OF THE ABOVE EXCEPTION, ANOTHER EXCEPTION OCCURRED:

TRACEBACK (MOST RECENT CALL LAST):
  FILE "C:\PROJETO\INFOGLOBO\EQUIPEQA\CONTINUOUS_DELIVERY\TRUNK\PYTHON\ENVIO_EMAIL\ENVIO_EMAIL.PY", LINE 66, IN ENVIAR_EMAIL
    SERVIDOR.SENDMAIL(SELF.REMETENTE, LISTA_DESTINATARIOS, SELF.MSG.AS_STRING())
  FILE "C:\USERS\RFONSECA\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON35-32\LIB\SMTPLIB.PY", LINE 872, IN SENDMAIL
    RAISE SMTPRECIPIENTSREFUSED(SENDERRS)
SMTPLIB.SMTPRECIPIENTSREFUSED: {' RENATO.FONSECA@INFOGLOBO.COM.BR': (421, B'4.7.0 SMTP4.INFOGLOBO.COM.BR ERROR: TOO MANY ERRORS'), ' VICTOR.FARIAS@INFOGLOBO.COM.BR': (554, B'5.7.1 <VICTOR.FARIAS@INFOGLOBO.COM.BR>: RELAY ACCESS DENIED'), ' GABRIELA.SILVA@INFOGLOBO.COM.BR': (554, B'5.7.1 <GABRIELA.SILVA@INFOGLOBO.COM.BR>: RELAY ACCESS DENIED'), 'RODRIGO.MAIA@INFOGLOBO.COM.BR': (554, B'5.7.1 <RODRIGO.MAIA@INFOGLOBO.COM.BR>: RELAY ACCESS DENIED')}

DEBUG:root: "2017-08-03 12:11:04" CLASSE: Email
DEBUG:root: "2017-08-03 12:11:04" CAMINHO DA CLASSE: python.envio_email.envio_email
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:11:05" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:11:07" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:11:08" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:11:24" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:11:26" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:11:29" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:11:44" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:11:44" FALHA - CRIACAO DO BACKUP.

DEBUG:root: "2017-08-03 12:11:44" CLASSE: BancoDados
DEBUG:root: "2017-08-03 12:11:44" CAMINHO DA CLASSE: python.scripts.bancoDados
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:11:45" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:11:47" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:11:48" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:12:03" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:12:06" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:12:07" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:12:22" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:12:22" NAO FOI ENCONTRADO NENHUM SCRIPT SQL PARA SER EXECUTADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:12:22" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:12:25" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:12:26" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:12:41" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:12:43" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:12:44" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:12:59" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:13:00" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:13:02" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:13:03" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:13:18" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:13:20" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:13:30" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:13:45" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:13:46" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:13:48" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:13:49" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:14:04" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:14:06" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:14:07" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:14:22" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:14:22" SUCESSO - FORAM CANCELADAS TODAS CONEXOES COM O BANCO DE DADOS
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:14:32" SUCESSO - NA CRIACAO DO SNAPSHOT
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:14:35" COMANDO EXECUATDO FLYWAY..:-USER=DEV_INFG_JENKINS -PASSWORD=95QLYAFTZ2S8 -URL=JDBC:JTDS:SQLSERVER://INFOSQLDSV/DEV_INFG_CELULAQUALIDADE_HOM -LOCATIONS=FILESYSTEM:C:\PROJETO\INFOGLOBO\EQUIPEQA\CONTINUOUS_DELIVERY\TRUNK\TESTES_WINDOWS/SCRIPTS\STG -TABLE=SCHEMA_MIGRATE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:14:41" DEPLOY REALIZADO COM SUCESSO.
VERSAO SVN...: 1.2
VERSAO STG...: 1.2
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:14:41" SUCESSO - FORAM CANCELADAS TODAS CONEXOES COM O BANCO DE DADOS
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:14:42" REALIZANDO O FAILBACK

DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:14:42" SUCESSO - AO HABILITAR USUARIO DA APLICACAO COM ACESSO COM O BANCO DE DADOS
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:14:42" SUCESSO --  REMOVIDO -- DEV_INFG_CELULAQUALIDADE_HOM_SNAPSHOT
DEBUG:root: "2017-08-03 12:14:42" CLASSE: BancoDados
DEBUG:root: "2017-08-03 12:14:42" CAMINHO DA CLASSE: python.scripts.bancoDados
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:14:48" ERRO TRACEBACK (MOST RECENT CALL LAST):
  FILE "PYMSSQL.PYX", LINE 635, IN PYMSSQL.CONNECT (PYMSSQL.C:10734)
  FILE "_MSSQL.PYX", LINE 1902, IN _MSSQL.CONNECT (_MSSQL.C:21821)
  FILE "_MSSQL.PYX", LINE 637, IN _MSSQL.MSSQLCONNECTION.__INIT__ (_MSSQL.C:6581)
  FILE "_MSSQL.PYX", LINE 1630, IN _MSSQL.MAYBE_RAISE_MSSQLDATABASEEXCEPTION (_MSSQL.C:17524)
_MSSQL.MSSQLDATABASEEXCEPTION: (18456, B'DB-LIB ERROR MESSAGE 20018, SEVERITY 11:\NGENERAL SQL SERVER ERROR: CHECK MESSAGES FROM THE SQL SERVER\NDB-LIB ERROR MESSAGE 20018, SEVERITY 14:\NGENERAL SQL SERVER ERROR: CHECK MESSAGES FROM THE SQL SERVER\NDB-LIB ERROR MESSAGE 20002, SEVERITY 9:\NADAPTIVE SERVER CONNECTION FAILED (INFOSQLDSV:1433)\N')

DURING HANDLING OF THE ABOVE EXCEPTION, ANOTHER EXCEPTION OCCURRED:

TRACEBACK (MOST RECENT CALL LAST):
  FILE "C:\PROJETO\INFOGLOBO\EQUIPEQA\CONTINUOUS_DELIVERY\TRUNK\PYTHON\SCRIPTS\BANCODADOS.PY", LINE 271, IN REMOVER_SNAPSHOT
    DATABASE=NOME_SNAPSHOT)
  FILE "PYMSSQL.PYX", LINE 641, IN PYMSSQL.CONNECT (PYMSSQL.C:10824)
PYMSSQL.OPERATIONALERROR: (18456, B'DB-LIB ERROR MESSAGE 20018, SEVERITY 11:\NGENERAL SQL SERVER ERROR: CHECK MESSAGES FROM THE SQL SERVER\NDB-LIB ERROR MESSAGE 20018, SEVERITY 14:\NGENERAL SQL SERVER ERROR: CHECK MESSAGES FROM THE SQL SERVER\NDB-LIB ERROR MESSAGE 20002, SEVERITY 9:\NADAPTIVE SERVER CONNECTION FAILED (INFOSQLDSV:1433)\N')

DURING HANDLING OF THE ABOVE EXCEPTION, ANOTHER EXCEPTION OCCURRED:

TRACEBACK (MOST RECENT CALL LAST):
  FILE "C:\PROJETO\INFOGLOBO\EQUIPEQA\CONTINUOUS_DELIVERY\TRUNK\PYTHON\ENVIO_EMAIL\ENVIO_EMAIL.PY", LINE 66, IN ENVIAR_EMAIL
    SERVIDOR.SENDMAIL(SELF.REMETENTE, LISTA_DESTINATARIOS, SELF.MSG.AS_STRING())
  FILE "C:\USERS\RFONSECA\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON35-32\LIB\SMTPLIB.PY", LINE 872, IN SENDMAIL
    RAISE SMTPRECIPIENTSREFUSED(SENDERRS)
SMTPLIB.SMTPRECIPIENTSREFUSED: {' RENATO.FONSECA@INFOGLOBO.COM.BR': (421, B'4.7.0 SMTP4.INFOGLOBO.COM.BR ERROR: TOO MANY ERRORS'), ' VICTOR.FARIAS@INFOGLOBO.COM.BR': (554, B'5.7.1 <VICTOR.FARIAS@INFOGLOBO.COM.BR>: RELAY ACCESS DENIED'), ' GABRIELA.SILVA@INFOGLOBO.COM.BR': (554, B'5.7.1 <GABRIELA.SILVA@INFOGLOBO.COM.BR>: RELAY ACCESS DENIED'), 'RODRIGO.MAIA@INFOGLOBO.COM.BR': (554, B'5.7.1 <RODRIGO.MAIA@INFOGLOBO.COM.BR>: RELAY ACCESS DENIED')}

DEBUG:root: "2017-08-03 12:14:48" CLASSE: Email
DEBUG:root: "2017-08-03 12:14:48" CAMINHO DA CLASSE: python.envio_email.envio_email
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:14:49" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:14:51" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:14:52" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:15:07" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:15:10" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:15:11" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:15:26" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:15:27" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:15:29" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:15:30" SUCESSO - BACKUP RESTAURADO
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-08-03 12:15:45" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:48:34" EXECUTANDO COMANDO: sqlcmd -S INFOSQLDSV -U  DEV_INFG_Jenkins -P 95QlyafTZ2s8 -i comandoSetOffLine.sql -o log_comandoSetOffLine.txt
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:48:36" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:48:37" EXECUTANDO COMANDO: sqlcmd -S INFOSQLDSV -U DEV_INFG_Jenkins -P 95QlyafTZ2s8 -i comandoRestaurarBackup.sql -o log_comandoRestaurarBackup.txt
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:48:37" SUCESSO - BACKUP RESTAURADO -DEV_INFG_CelulaQualidade_HOM
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:48:42" EXECUTANDO COMANDO: sqlcmd -S INFOSQLDSV -U DEV_INFG_Jenkins -P 95QlyafTZ2s8 -i comandoSetOnLine.sql -o log_comandoSetOnLine.txt
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:48:42" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:48:43" EXECUTANDO COMANDO: sqlcmd -S INFOSQLDSV -U  DEV_INFG_Jenkins -P 95QlyafTZ2s8 -i comandoSetOffLine.sql -o log_comandoSetOffLine.txt
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:48:45" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:48:47" EXECUTANDO COMANDO: sqlcmd -S INFOSQLDSV -U DEV_INFG_Jenkins -P 95QlyafTZ2s8 -i comandoRestaurarBackup.sql -o log_comandoRestaurarBackup.txt
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:48:47" SUCESSO - BACKUP RESTAURADO -DEV_INFG_CelulaQualidade_DSV
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:48:53" EXECUTANDO COMANDO: sqlcmd -S INFOSQLDSV -U DEV_INFG_Jenkins -P 95QlyafTZ2s8 -i comandoSetOnLine.sql -o log_comandoSetOnLine.txt
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:48:53" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:48:53" EXECUTANDO COMANDO: sqlcmd -S INFOSQLDSV -U INFG_Jenkins -P 95QlyafTZ2s8 -i comandoCriarBackup.sql -o log_comandoCriarBackup.txt
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:48:53" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:48:54" EXECUTANDO COMANDO: sqlcmd -S INFOSQLDSV -U  DEV_INFG_Jenkins -P 95QlyafTZ2s8 -i comandoSetOffLine.sql -o log_comandoSetOffLine.txt
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:48:56" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:48:59" EXECUTANDO COMANDO: sqlcmd -S INFOSQLDSV -U DEV_INFG_Jenkins -P 95QlyafTZ2s8 -i comandoRestaurarBackup.sql -o log_comandoRestaurarBackup.txt
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:48:59" SUCESSO - BACKUP RESTAURADO - INFG_CelulaQualidade_DSV
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:49:04" EXECUTANDO COMANDO: sqlcmd -S INFOSQLDSV -U DEV_INFG_Jenkins -P 95QlyafTZ2s8 -i comandoSetOnLine.sql -o log_comandoSetOnLine.txt
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:49:04" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:49:04" EXECUTANDO COMANDO: sqlcmd -S INFOSQLDSV -U DEV_INFG_Jenkins -P 95QlyafTZ2s8 -i comandoRenomearLogicalNames.sql -o log_comandoRenomearLogicalNames.txt
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:49:04" SUCESSO - LOGICAL NAMES RENOMEAROS - INFG_CelulaQualidade_DSV
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:49:05" EXECUTANDO COMANDO: sqlcmd -S INFOSQLDSV -U DEV_INFG_Jenkins -P 95QlyafTZ2s8 -i comandoTrocarUsuarioPrdParaStg.sql -o log_comandoTrocarUsuarioPrdParaStg.txt
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:49:05" SUCESSO - USUARIOS TROCADOS DE PRD PARA STG - INFG_CelulaQualidade_DSV
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:49:06" EXECUTANDO COMANDO: sqlcmd -S INFOSQLDSV -U DEV_INFG_Jenkins -P 95QlyafTZ2s8 -i comandoCriarBackup.sql -o log_comandoCriarBackup.txt
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:49:06" SUCESSO - CRIACAO DO BACKUP
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:49:12" EXECUTANDO COMANDO: sqlcmd -S INFOSQLDSV -U  DEV_INFG_Jenkins -P 95QlyafTZ2s8 -i comandoSetOffLine.sql -o log_comandoSetOffLine.txt
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:49:14" SUCESSO - COLOCAR O BANCO DE STG OFFLINE
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:49:17" EXECUTANDO COMANDO: sqlcmd -S INFOSQLDSV -U DEV_INFG_Jenkins -P 95QlyafTZ2s8 -i comandoRestaurarBackup.sql -o log_comandoRestaurarBackup.txt
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:49:17" SUCESSO - BACKUP RESTAURADO -DEV_INFG_CelulaQualidade_DSV
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:49:22" EXECUTANDO COMANDO: sqlcmd -S INFOSQLDSV -U DEV_INFG_Jenkins -P 95QlyafTZ2s8 -i comandoSetOnLine.sql -o log_comandoSetOnLine.txt
DEBUG:root:
DEBUG:root:
DEBUG:root: "2017-11-24 13:49:22" SUCESSO - VOLTAR O BANCO DE STG ONLINE
DEBUG:root:
